export const Actions = Object.freeze({
    ON_TEAM_APPLY: 'ON_TEAM_APPLY',
    ON_NEXT_QUESTION: 'ON_NEXT_QUESTION',
    ON_NEXT_ROUND: 'ON_NEXT_ROUND',
    ON_ACTION: 'ON_ACTION',
    ON_ANSWER_SUBMIT: 'ON_ANSWER_SUBMIT',
    ON_QUESTION_CLOSED: 'ON_QUESTION_CLOSED',
    ON_QUIZ_NIGHT_SCORE: 'ON_QUIZ_NIGHT_SCORE',
    ON_QUIZ_NIGHT_END: 'ON_QUIZ_NIGHT_END'
});