export const Actions = Object.freeze({
    ON_QUIZ_NIGHT_START: 'ON_QUIZ_NIGHT_START',
    ON_NEXT_QUESTION: 'ON_NEXT_QUESTION',
    ON_NEXT_ROUND: 'ON_NEXT_ROUND',
    ON_TEAM_ANSWER: 'ON_TEAM_ANSWER',
    ON_ANSWERS_REVEAL: 'ON_ANSWERS_REVEAL',
    ON_SCORE: 'ON_SCORE',
    SET_QUESTION: 'SET_QUESTION',
    ON_ROUND_END: 'ON_ROUND_END'
});