export const Actions = Object.freeze({
    OPEN_QUIZ_NIGHT: 'OPEN_QUIZ_NIGHT',
    ON_TEAM_APPROVE: 'ON_TEAM_APPROVE',
    ON_TEAM_REJECTED: 'ON_TEAM_REJECTED',
    ON_CATEGORIES_RECEIVED: 'ON_CATEGORIES_RECEIVED',
    ON_CATEGORY_ADD: 'ON_CATEGORY_ADD',
    ON_CATEGORY_REMOVE: 'ON_CATEGORY_REMOVE',
    ON_ANSWER_REJECT: 'ON_ANSWER_REJECT',
    ON_ANSWER_APPROVE: 'ON_ANSWER_APPROVE',
    ON_CLOSE_QUESTION: 'ON_CLOSE_QUESTION',
    ON_OPEN_QUESTION: 'ON_OPEN_QUESTION',
    ON_CLOSE_QUIZ_NIGHT: 'ON_CLOSE_QUIZ_NIGHT',
    ON_NEXT_ROUND: 'ON_NEXT_ROUND',
    ON_QUIZ_NIGHT_RESULT: 'ON_QUIZ_NIGHT_RESULT',
    ON_TEAM_APPLICATIONS_RECEIVED: 'ON_TEAM_APPLICATIONS_RECEIVED',
    CHANGE_ROUND_NUMBER: 'CHANGE_ROUND_NUMBER',
    ON_QUESTIONS_RECEIVED: 'ON_QUESTIONS_RECEIVED'
});