export const Actions = Object.freeze({
    OPEN_QUIZ_NIGHT: 'OPEN_QUIZ_NIGHT',
    ON_OPEN_QUIZ_NIGHT: 'ON_OPEN_QUIZ_NIGHT',
    ON_TEAM_APPLY: 'ON_TEAM_APPLY',
    ON_TEAM_APPROVE: 'ON_TEAM_APPROVE',
    ON_TEAM_REJECTED: 'ON_TEAM_REJECTED',
    ON_CATEGORY_ADD: 'ON_CATEGORY_ADD',
    ON_CATEGORY_REMOVE: 'ON_CATEGORY_REMOVE',
    ON_QUESTIONS_RECEIVE: 'ON_QUESTIONS_RECEIVE',
    ON_ANSWER: 'ON_ANSWER',
    ON_ANSWER_REJECT: 'ON_ANSWER_REJECT',
    ON_ANSWER_APPROVE: 'ON_ANSWER_APPROVE',
    ON_CLOSE_QUESTION: 'ON_CLOSE_QUESTION',
    ON_OPEN_QUESTION: 'ON_OPEN_QUESTION',
    ON_CLOSE_QUIZ_NIGHT: 'ON_CLOSE_QUIZ_NIGHT',
    ON_NEXT_ROUND: 'ON_NEXT_ROUND',
    ON_QUIZ_NIGHT_RESULT: 'ON_QUIZ_NIGHT_RESULT'
});