export const SharedActions = Object.freeze({
    NEXT_QUESTION: 'NEXT_QUESTION',
    NEXT_ROUND: 'NEXT_ROUND',
    NIGHT_END: 'NIGHT_END',
    CHANGE_TITLE: 'CHANGE_TITLE',
    SET_QUIZ_PIN: 'SET_QUIZ_PIN',
    SET_ROUND_NUMBER: 'SET_ROUND_NUMBER',
    SET_QUESTION_NUMBER: 'SET_QUESTION_NUMBER',
    ON_TEAM_APPROVAL: 'ON_TEAM_APPROVAL',
    ON_TEAM_SCORES_RECEIVED: 'ON_TEAM_SCORES_RECEIVED'
});