export const SharedActions = Object.freeze({
    NEXT_QUESTION: 'NEXT_QUESTION',
    NEXT_ROUND: 'NEXT_ROUND',
    NIGHT_END: 'NIGHT_END',
    CHANGE_TITLE: 'CHANGE_TITLE',
    ON_OPEN_QUIZ_NIGHT: 'ON_OPEN_QUIZ_NIGHT'
});