# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.19.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --prefix clients/shared/shared
    - run: npm run build:linux --prefix clients/shared/shared
    - run: npm i --prefix clients/shared/dist
    - run: npm i --prefix clients/team
    - run: npm i --prefix clients/master
    - run: npm i --prefix clients/scoreboard
    - run: npm run build --prefix clients/team
    - run: npm run build --prefix clients/master
    - run: npm run build --prefix clients/scoreboard
